services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8081:8080' 

volumes:
  data: